- id: swag-fmt
  name: swag-fmt
  entry: run-swag-fmt.sh
  language: script
  always_run: false
  fail_fast: false
  verbose: false
  require_serial: true
  description: 'Run swag fmt to format Swag annotations in your code.'
  args: []

- id: swag-init
  name: swag-init
  entry: run-swag-init.sh
  language: script
  always_run: false
  fail_fast: false
  verbose: false
  require_serial: true
  description: 'Run swag init to generate Swagger docs from Swag annotations, and generate the required files.'
  args: []
